/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtomThemeToggle: typeof import('./src/components/atoms/AtomThemeToggle/AtomThemeToggle.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardAction: typeof import('./src/components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    OrganismDesktopHeader: typeof import('./src/components/organisms/OrganismDesktopHeader/OrganismDesktopHeader.vue')['default']
    OrganismGetCurrentWeather: typeof import('./src/components/organisms/OrganismGetCurrentWeather/OrganismGetCurrentWeather.vue')['default']
    OrganismMobileHeader: typeof import('./src/components/organisms/OrganismMobileHeader/OrganismMobileHeader.vue')['default']
    OrganismWebHeader: typeof import('./src/components/organisms/OrganismWebHeader/OrganismWebHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/ui/table/Table.vue')['default']
    TableBody: typeof import('./src/components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./src/components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./src/components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./src/components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./src/components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./src/components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./src/components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./src/components/ui/table/TableRow.vue')['default']
    TemplateDesktop: typeof import('./src/components/templates/TemplateDesktop/TemplateDesktop.vue')['default']
    TemplateMobile: typeof import('./src/components/templates/TemplateMobile/TemplateMobile.vue')['default']
    TemplateWeb: typeof import('./src/components/templates/TemplateWeb/TemplateWeb.vue')['default']
    Textarea: typeof import('./src/components/ui/textarea/Textarea.vue')['default']
  }
}
