/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/organisms/BaseFooter/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/organisms/BaseHeader/BaseHeader.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    FloatingHeader: typeof import('./src/components/organisms/FloatingHeader/FloatingHeader.vue')['default']
    FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    LoginSignupForm: typeof import('./src/components/organisms/LoginSignupForm/LoginSignupForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestTwo: typeof import('./src/components/atoms/TestTwo/TestTwo.vue')['default']
    ThemeToggle: typeof import('./src/components/molecules/ThemeToggle/ThemeToggle.vue')['default']
  }
}

// For TSX support
declare global {
  const BaseFooter: typeof import('./src/components/organisms/BaseFooter/BaseFooter.vue')['default']
  const BaseHeader: typeof import('./src/components/organisms/BaseHeader/BaseHeader.vue')['default']
  const Button: typeof import('./src/components/ui/button/Button.vue')['default']
  const Card: typeof import('./src/components/ui/card/Card.vue')['default']
  const CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
  const CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
  const CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
  const CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
  const CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
  const FloatingHeader: typeof import('./src/components/organisms/FloatingHeader/FloatingHeader.vue')['default']
  const FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
  const FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
  const FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
  const FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
  const FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
  const Input: typeof import('./src/components/ui/input/Input.vue')['default']
  const Label: typeof import('./src/components/ui/label/Label.vue')['default']
  const LoginSignupForm: typeof import('./src/components/organisms/LoginSignupForm/LoginSignupForm.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TestTwo: typeof import('./src/components/atoms/TestTwo/TestTwo.vue')['default']
  const ThemeToggle: typeof import('./src/components/molecules/ThemeToggle/ThemeToggle.vue')['default']
}