allowBuilds:
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - playwright-core@1.61.1
  - playwright@1.61.1
  - '@vue/devtools-core@8.1.5'
  - '@vue/devtools-kit@8.1.5'
  - '@vue/devtools-shared@8.1.5'
  - prettier@3.9.1
  - vite-plugin-vue-devtools@8.1.5
  - '@lucide/vue@1.23.0'
  - '@types/node@26.1.0'
  - linkify-it@5.0.2
  - markdown-it@14.3.0
  - '@oxlint/binding-android-arm-eabi@1.74.0'
  - '@oxlint/binding-android-arm64@1.74.0'
  - '@oxlint/binding-darwin-arm64@1.74.0'
  - '@oxlint/binding-darwin-x64@1.74.0'
  - '@oxlint/binding-freebsd-x64@1.74.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.74.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.74.0'
  - '@oxlint/binding-linux-arm64-gnu@1.74.0'
  - '@oxlint/binding-linux-arm64-musl@1.74.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.74.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.74.0'
  - '@oxlint/binding-linux-riscv64-musl@1.74.0'
  - '@oxlint/binding-linux-s390x-gnu@1.74.0'
  - '@oxlint/binding-linux-x64-gnu@1.74.0'
  - '@oxlint/binding-linux-x64-musl@1.74.0'
  - '@oxlint/binding-openharmony-arm64@1.74.0'
  - '@oxlint/binding-win32-arm64-msvc@1.74.0'
  - '@oxlint/binding-win32-ia32-msvc@1.74.0'
  - '@oxlint/binding-win32-x64-msvc@1.74.0'
  - '@vitejs/plugin-vue@6.0.8'
  - oxlint@1.74.0
  - '@storybook/addon-a11y@10.5.2'
  - '@storybook/addon-docs@10.5.2'
  - '@storybook/addon-onboarding@10.5.2'
  - '@storybook/addon-vitest@10.5.2'
  - '@storybook/builder-vite@10.5.2'
  - '@storybook/csf-plugin@10.5.2'
  - '@storybook/react-dom-shim@10.5.2'
  - '@storybook/vue3-vite@10.5.2'
  - '@storybook/vue3@10.5.2'
  - '@tailwindcss/node@4.3.3'
  - '@tailwindcss/oxide-android-arm64@4.3.3'
  - '@tailwindcss/oxide-darwin-arm64@4.3.3'
  - '@tailwindcss/oxide-darwin-x64@4.3.3'
  - '@tailwindcss/oxide-freebsd-x64@4.3.3'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.3'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.3'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.3'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.3'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.3'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.3'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.3'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.3'
  - '@tailwindcss/oxide@4.3.3'
  - '@tailwindcss/vite@4.3.3'
  - eslint-plugin-storybook@10.5.2
  - storybook@10.5.2
  - tailwindcss@4.3.3
  - vite@8.1.5
